version: '2.1'
services:
  cd4pe:
    container_name: cd4pe
    ports:
      - "8080:8080"
      - "7000:7000"
      - "8000:8000"
    image: puppet/continuous-delivery-for-puppet-enterprise:latest
    environment:
      DB_ENDPOINT: mysql://db:3306/cd4pe
      USER: cd4pe
      MYSQL_PWD: puppetlabs
    depends_on:
      - db
      - artifactory
  db:
    image: mysql:5.7
    container_name: cd4pe_db
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: puppetlabs
       MYSQL_DATABASE: cd4pe
       MYSQL_USER: cd4pe
       MYSQL_PASSWORD: puppetlabs
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:5.8.3
    container_name: cd4pe_artifactory
    ports:
      - 8081:8081
    volumes:
      - data_s3:/var/opt/jfrog/artifactory
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    ports:
      - 90:80
      - 8090:8080
      - 453:443
      - 32:22

volumes:
  db_data:
    name: cd4pe_db_data
  data_s3:
    name: cd4pe_data_s3
